# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-23 00:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Valeu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=400)),
                ('create_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'valeu',
            },
        ),
    ]
