# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-25 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Valeu',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('team_id', models.CharField(max_length=50)),
                ('team_domain', models.CharField(max_length=500)),
                ('channel_id', models.CharField(max_length=50)),
                ('channel_name', models.CharField(max_length=500)),
                ('user_id_from', models.CharField(max_length=80)),
                ('user_name_from', models.CharField(max_length=500)),
                ('user_id_to', models.CharField(max_length=80)),
                ('user_name_to', models.CharField(max_length=500)),
                ('command', models.CharField(max_length=100)),
                ('text', models.CharField(max_length=800)),
                ('response_url', models.CharField(max_length=600)),
                ('create_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'valeu',
            },
        ),
    ]
