# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-25 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('team_id', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=500)),
                ('status', models.BooleanField()),
                ('real_name', models.CharField(max_length=500)),
                ('first_name', models.CharField(max_length=500)),
                ('last_name', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=700)),
                ('email', models.CharField(max_length=200)),
                ('image_24', models.CharField(max_length=300)),
                ('image_32', models.CharField(max_length=300)),
                ('image_48', models.CharField(max_length=300)),
                ('image_72', models.CharField(max_length=300)),
                ('image_192', models.CharField(max_length=300)),
                ('image_original', models.CharField(max_length=300)),
                ('create_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
